version: "1.0"
info:
  model: int-scaffold
packages:
- name: VersionProject
  gitServerName: Rahul
  gitUrl: https://github.com/Rahul-Sivakumar-IBM
  gitUsername: Rahul-Sivakumar-IBM
  gitBranch: main
- name: JcHelloWorldAPI
  gitServerName: Rahul
  gitUrl: https://github.com/johnpcarter
  gitUsername: Rahul-Sivakumar-IBM
  gitTag: v1.0.0
services:
- serviceName: project.version.integrations:DAF1
  packages:
  - name: VersionProject
    version: 1.1.1
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 12.1.0.0.1070
